@startuml

skinparam actorStyle Hollow 

Движок --> (1. Обнулить энкодер)
Движок --> (2. Выставить скорость)
Движок --> (3. Выставить режим)
Движок --> (4. Выставить целевую позицию)
Движок --> (5. Приехать в позицию)


Манипулятор --> (1. Приехать в позицию)

usbcan_шина --> (1. Подключиться) 
usbcan_шина --> (2. Отослать команду) 
usbcan_шина --> (1. Отключиться) 

@enduml