import codecs
import can
import servo_realisation.commands_constructor.input_output_realisation
import servo_realisation.control_objects.input_output_realisation
import binascii
import servo_realisation.commands_reader.input_output_realisation

import servo_realisation.commands_abstraction.input_output_realisation



servo_1 = servo_realisation.control_objects.input_output_realisation.create_servo_object_can(
    servo_id=1
)

ser_1 = servo_realisation.commands_abstraction.input_output_realisation.create_servo_commands_abstraction_can(servo_object=servo_1)
