import servo_realisation.servo_object.servo_interface
import servo_realisation.commands_constructor.commands_constructor
import servo_realisation.commands_constructor.commands_constructor_abstraction


def create_servo_command_constructor(servo_object):
    commands_constructor = servo_realisation.commands_constructor.commands_constructor.CommandConstructor(servo_object=servo_object)
    commands_constructor_abs = servo_realisation.commands_constructor.commands_constructor_abstraction.CommandConstructorAbstraction(commands_constructor)
    return commands_constructor_abs
